#VERSION?
version.version=xhc_2024?8?6? 17?40? PDB
#ip benDi
#server.address=192.168.4.240
#server.address=192.168.6.239
server.address=127.0.0.1
server.port=9999
#ip fwq
#server.address=192.168.6.10
#server.port=16162
#time-zone
spring.jackson.time-zone=GMT+8
spring.jackson.date-format=yyyy-MM-dd HH:mm:ss
#mysql
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.datasource.url=jdbc:mysql://127.0.0.1:3306/test0210?characterEncoding=utf-8&useUnicode=true&autoReconnect=true&useTimezone=true&serverTimezone=GMT%2B8
#spring.datasource.username=root
#spring.datasource.password=123456
#kingbase
spring.datasource.driver-class-name=com.kingbase8.Driver
#spring.datasource.url=jdbc:kingbase8://192.168.6.13:54321/sp_wms
spring.datasource.url=jdbc:kingbase8://127.0.0.1:54321/sp_wms
spring.datasource.username=system
spring.datasource.password=123456
#sqlserver
#driver=com.microsoft.sqlserver.jdbc.SQLServerDriver
#url=jdbc:sqlserver://127.0.0.1:1433;Database=NJ528.DB
#username=sa
#password=123456
#mybatis
#mybatis.mapper-locations=classpath:mapper/*Mapper.xml
#mybatis.executor-type=batch
#mybatis.type-aliases-package=com.example.wms.entity.system
#swagger
spring.mvc.pathmatch.matching-strategy=ant_path_matcher
#camel
mybatis-plus.configuration.map-underscore-to-camel-case=false
#SQLlog mybatis-plus
#mybatis-plus.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl
#XZK API
apiX.status=http://192.168.6.10:8888/api/shuttle/status
apiX.inbound=http://192.168.6.10:8888/api/shuttle/inbound
apiX.outbound=http://192.168.6.10:8888/api/shuttle/outbound
apiX.task=http://192.168.6.10:8888/api/shuttle/task
apiX.cmdopt=http://192.168.6.10:8888/api/shuttle/cmdopt
#DJK API
apiD.taskReceive=http://192.168.6.10:8082/fromWms/taskReceive
apiD.taskChange=http://192.168.6.10:8082/fromWms/taskChange
apiD.taskCancel=http://192.168.6.10:8082/fromWms/taskCancel
apiD.taskPriority=http://192.168.6.10:8082/fromWms/taskPriority
apiD.cargoLocationStatus=http://192.168.6.10:8082/fromWms/cargoLocationStatus
apiD.cargoLocationSyn=http://192.168.6.10:8082/fromWms/cargoLocationSyn
apiD.cargoNoSyn=http://192.168.6.10:8082/fromWms/cargoNoSyn
apiD.portModel=http://192.168.6.10:8082/fromWms/portModel
apiD.deviceStatus=http://192.168.6.10:8082/fromWms/deviceStatus
#ZDH API
apiZ.wmsWhTask=http://192.168.6.10:18003/wcs/wmsWhTask
apiZ.wmsSortTask=http://192.168.6.10:18003/wcs/wmsSortTask
apiZ.wmsDpsTask=http://192.168.6.10:18003/wcs/wmsDpsTask
apiZ.trussBoxTask=http://192.168.6.10:18003/wcs/machine_task
apiZ.machineSort=http://192.168.4.218:18003/wcs/machine_sort
#AGV API
apiAGV.TaskDownload=http://192.168.6.11:9101/api/ExternalTask/TaskDownload
apiAGV.TaskCancel=http://192.168.6.11:9101/api/ExternalTask/TaskCancel
apiAGV.AGVParameter=http://192.168.6.11:9101/api/ExternalTask/AgvState
#CTU API
apiCTU.TaskDownload=http://192.168.3.14:8181/rcms/services/rest/hikRpcService/taskDownload
apiCTU.TaskCancel=http://192.168.3.14:8181/rcms/services/rest/hikRpcService/taskCancel
apiCTU.AGVParameter=http://192.168.3.14:8182/rcms-dps/rest/queryAgvStatus
#\u76D8\u5E93
check.up=http://192.168.4.201:8080/qicai/panKu/back/qc/for/manager

#sdk
led.x = 0
led.y = 0
led.width = 320
led.height = 192
led.ip = 192.168.6.243
led.port = 5005
led.timeout = 30000
